<?php

namespace ContainerYo7vf6a;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_VLDuBr1Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.VLDuBr1' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.VLDuBr1'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\PizzaController::detailAction' => ['privates', '.service_locator.qAjAfyO', 'get_ServiceLocator_QAjAfyOService', true],
            'App\\Controller\\PizzaController::listeAction' => ['privates', '.service_locator.qAjAfyO', 'get_ServiceLocator_QAjAfyOService', true],
            'App\\Controller\\PizzaioloController::disponiblesAction' => ['privates', '.service_locator.tYODufU', 'get_ServiceLocator_TYODufUService', true],
            'App\\Controller\\PizzeriaController::detailAction' => ['privates', '.service_locator.bQL9fNU', 'get_ServiceLocator_BQL9fNUService', true],
            'App\\Controller\\PizzeriaController::listeAction' => ['privates', '.service_locator.bQL9fNU', 'get_ServiceLocator_BQL9fNUService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'App\\Controller\\PizzaController:detailAction' => ['privates', '.service_locator.qAjAfyO', 'get_ServiceLocator_QAjAfyOService', true],
            'App\\Controller\\PizzaController:listeAction' => ['privates', '.service_locator.qAjAfyO', 'get_ServiceLocator_QAjAfyOService', true],
            'App\\Controller\\PizzaioloController:disponiblesAction' => ['privates', '.service_locator.tYODufU', 'get_ServiceLocator_TYODufUService', true],
            'App\\Controller\\PizzeriaController:detailAction' => ['privates', '.service_locator.bQL9fNU', 'get_ServiceLocator_BQL9fNUService', true],
            'App\\Controller\\PizzeriaController:listeAction' => ['privates', '.service_locator.bQL9fNU', 'get_ServiceLocator_BQL9fNUService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
        ], [
            'App\\Controller\\PizzaController::detailAction' => '?',
            'App\\Controller\\PizzaController::listeAction' => '?',
            'App\\Controller\\PizzaioloController::disponiblesAction' => '?',
            'App\\Controller\\PizzeriaController::detailAction' => '?',
            'App\\Controller\\PizzeriaController::listeAction' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\PizzaController:detailAction' => '?',
            'App\\Controller\\PizzaController:listeAction' => '?',
            'App\\Controller\\PizzaioloController:disponiblesAction' => '?',
            'App\\Controller\\PizzeriaController:detailAction' => '?',
            'App\\Controller\\PizzeriaController:listeAction' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
