<?php

namespace ContainerYo7vf6a;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPizzeriaDaoService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\Dao\PizzeriaDao' shared autowired service.
     *
     * @return \App\Service\Dao\PizzeriaDao
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'Dao'.\DIRECTORY_SEPARATOR.'PizzeriaDao.php';

        return $container->privates['App\\Service\\Dao\\PizzeriaDao'] = new \App\Service\Dao\PizzeriaDao(($container->privates['App\\Repository\\PizzeriaRepository'] ?? $container->load('getPizzeriaRepositoryService')));
    }
}
