<?php

namespace ContainerYo7vf6a;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPizzaDaoService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\Dao\PizzaDao' shared autowired service.
     *
     * @return \App\Service\Dao\PizzaDao
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'Dao'.\DIRECTORY_SEPARATOR.'PizzaDao.php';

        return $container->privates['App\\Service\\Dao\\PizzaDao'] = new \App\Service\Dao\PizzaDao(($container->privates['App\\Repository\\PizzaRepository'] ?? $container->load('getPizzaRepositoryService')));
    }
}
