<?php

namespace ContainerYo7vf6a;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPizzaioloDaoService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\Dao\PizzaioloDao' shared autowired service.
     *
     * @return \App\Service\Dao\PizzaioloDao
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'Dao'.\DIRECTORY_SEPARATOR.'PizzaioloDao.php';

        return $container->privates['App\\Service\\Dao\\PizzaioloDao'] = new \App\Service\Dao\PizzaioloDao(($container->privates['App\\Repository\\PizzaioloRepository'] ?? $container->load('getPizzaioloRepositoryService')));
    }
}
